apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/rancher`)
      kind: Rule
      services:
        - name: rancher
          port: 80
  tls:
    secretName: traefik-cert
