apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-catchall
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: rancher
          port: 80
  tls:
    secretName: traefik-cert
